/*
* Copyright (c) 2002-2007 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Camera Application Engine Trace Definitions
*
*/


// Created by TraceBuilder.Autogen 0.20.1
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CAMAPPENGINETRACEDEFINITIONS_H__
#define __CAMAPPENGINETRACEDEFINITIONS_H__

#include <autogen_symbian_trace_config.h>
// Empty macro for TraceBuilder data definitions
#define TB_DATA(x)

#undef CAMAPPENGINE_ERROR
#define CAMAPPENGINE_ERROR 0xe1
#undef CAMAPPENGINE_API
#define CAMAPPENGINE_API 0xe2
#undef CAMAPPENGINE_FLOW
#define CAMAPPENGINE_FLOW 0xe3
#undef CAMAPPENGINE_PERFORMANCE
#define CAMAPPENGINE_PERFORMANCE 0xe4

RES_BEGIN( RESOURCE_TRC_SYMBIAN, AUTOGEN_NO_RESOURCE_ID, CAMAPPENGINE_TRACE, "CAMAPPENGINE", "", FALSE )
	
	TRACE_GROUP_BEGIN( CAMAPPENGINE_ERROR, "CamAppEngine_Error:", ON )
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( CAMAPPENGINE_API, "CamAppEngine_API:", ON )
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( CAMAPPENGINE_FLOW, "CamAppEngine_Flow:", ON )
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( CAMAPPENGINE_PERFORMANCE, "CamAppEngine_Perf:", ON )
		
		TRACE_BEGIN( CAE_ENGINE_INIT_START, "e_CAM_ENG_INIT 1" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
		
		TRACE_BEGIN( CAE_ENGINE_INIT_END, "e_CAM_ENG_INIT 0" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
		
		TRACE_BEGIN( CAE_ENGINE_STILL_INIT_START, "e_CAM_ENG_STILL_INIT 1" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
		
		TRACE_BEGIN( CAE_ENGINE_STILL_INIT_END, "e_CAM_ENG_STILL_INIT 0" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
		
		TRACE_BEGIN( CAE_ENGINE_SHOT_TO_STILL_START, "e_CAM_ENG_SHOT_TO_STILL 1" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
		
		TRACE_BEGIN( CAE_ENGINE_SHOT_TO_STILL_END, "e_CAM_ENG_SHOT_TO_STILL 0" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
		
		TRACE_BEGIN( CAE_ENGINE_OPERATIONS_START, "e_CAM_CAE_OPERATIONS 1" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
		
		TRACE_BEGIN( CAE_ENGINE_OPERATIONS_END, "e_CAM_CAE_OPERATIONS 0" )
			
			AUTOGEN_BTRACE_HEADER
			
			AUTOGEN_BTRACE_TIMESTAMP
			
			AUTOGEN_BTRACE_GROUP_TRACE_ID
		
		TRACE_END()
	
	TRACE_GROUP_END()

RES_END

#endif
